---
name: ADT Pulse MQTT - BigThunderSR Test - Alpha
version: 3.3.1a
slug: x_adtpulsemqtt_bigthundersr_test_alpha
description: ADT Pulse Bridge using MQTT - Alpha Test Version
codenotary: bigthundersr@outlook.com
url: https://github.com/BigThunderSR/adt-pulse-mqtt
#startup: application
#boot: auto
#host_network: false
arch:
  - aarch64
  - amd64
  - armhf
map:
  - share:rw
  - ssl
image: "ghcr.io/bigthundersr/adt-pulse-mqtt-test-alpha-{arch}"
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  pulse_login:
    username: ""
    password: ""
    fingerprint: ""
  mqtt_host: core-mosquitto
  mqtt_url: ""
  mqtt_connect_options:
    username: ""
    password: ""
  alarm_state_topic: home/alarm/state
  alarm_command_topic: home/alarm/cmd
  zone_state_topic: adt/zone
  smartthings_topic: smartthings
  smartthings: false
schema:
  ssl: bool
  certfile: str
  keyfile: str
  pulse_login:
    username: str
    password: str
    fingerprint: str
  mqtt_host: str
  mqtt_url: str?
  mqtt_connect_options:
    username: str
    password: str
  alarm_state_topic: str
  alarm_command_topic: str
  zone_state_topic: str
  smartthings_topic: str
  smartthings: bool
