ARG BUILD_FROM=balenalib/armv7hf-alpine:3.13-run
FROM $BUILD_FROM

ENV LANG C.UTF-8
ENV NODE_ENV production
ENV QEMU_EXECVE 1

RUN [ "cross-build-start" ]

# Install node and npm (Node 14 LTS)
RUN apk add --update nodejs=~14
RUN apk add --update npm=~14

## Install node and npm (Node 16 LTS)
#RUN apk add --update nodejs=~16
#RUN apk add --update npm=~16

WORKDIR /usr/src/app

# Install app dependencies
COPY package.json .
RUN /usr/bin/npm install

# Bundle app source
COPY . .

# Copy data for add-on
COPY run.sh /
RUN chmod a+x /run.sh  

RUN [ "cross-build-end" ]

CMD [ "/run.sh" ]

#  Labels 

ARG BUILD_DESCRIPTION="ADT Pulse bridge for Home Assistant using MQTT"
ARG BUILD_NAME="ADT Pulse bridge for Home Assistant using MQTT Node18"
ARG BUILD_REPOSITORY="BigThunderSR/adt-pulse-mqtt"

LABEL \
    maintainer="BigThunderSR (https://github.com/BigThunderSR)" \
    org.opencontainers.image.title="${BUILD_NAME}" \
    org.opencontainers.image.description="${BUILD_DESCRIPTION}" \
    org.opencontainers.image.vendor="ADT Pulse bridge for Home Assistant using MQTT" \
    org.opencontainers.image.authors="BigThunderSR (https://github.com/BigThunderSR)" \    
    org.opencontainers.image.url="https://github.com/BigThunderSR" \
    org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" \
    org.opencontainers.image.documentation="https://github.com/${BUILD_REPOSITORY}/blob/main/README.md" 