ARG BUILD_FROM=balenalib/amd64-alpine:3.20-run
FROM $BUILD_FROM

ENV LANG C.UTF-8
ENV NODE_ENV production

# Install node and npm (Node 14 LTS)
#RUN apk add --update nodejs=~14
#RUN apk add --update nodejs-npm=~14

# Install node and npm (Node 18 LTS)
RUN apk add --no-cache \
    nodejs \
    npm

WORKDIR /usr/src/app

# Install app dependencies
COPY ["package.json", "/usr/src/app/"]
COPY ["package-lock.json", "/usr/src/app/"]

# RUN npm install --production
RUN npm ci --omit=dev --no-fund

# Bundle app source
COPY ./ /usr/src/app/

# Copy data for add-on
COPY run.sh /usr/src/app/
RUN chmod a+x /usr/src/app/run.sh

CMD [ "/usr/src/app/run.sh" ]

#  Labels 

ARG BUILD_DESCRIPTION="ADT Pulse bridge for Home Assistant using MQTT"
ARG BUILD_NAME="ADT Pulse bridge for Home Assistant using MQTT - amd64"
ARG BUILD_REPOSITORY="BigThunderSR/adt-pulse-mqtt"

LABEL \
    maintainer="BigThunderSR (https://github.com/BigThunderSR)" \
    org.opencontainers.image.title="${BUILD_NAME}" \
    org.opencontainers.image.description="${BUILD_DESCRIPTION}" \
    org.opencontainers.image.vendor="ADT Pulse bridge for Home Assistant using MQTT" \
    org.opencontainers.image.authors="BigThunderSR (https://github.com/BigThunderSR)" \    
    org.opencontainers.image.url="https://github.com/BigThunderSR" \
    org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" \
    org.opencontainers.image.documentation="https://github.com/${BUILD_REPOSITORY}/blob/main/README.md" 